package com.example.demo-checkout.hermetic;

import org.springframework.web.bind.annotation.*;
import org.springframework.http.ResponseEntity;
import java.util.Map;

/**
 * Hermetic Server - Sample Data Controller
 * 
 * Use this API to get sample payloads for testing.
 * Generated by TARS - Test Automation and Review System
 */
@RestController
@RequestMapping("/hermetic")
@Profile("hermetic")
public class SampleDataController {

    @GetMapping("/sample-data/{entityType}")
    public ResponseEntity<Object> getSampleData(
            @PathVariable String entityType) {
        
        // TODO: Return sample data based on entity type
        return ResponseEntity.ok(Map.of(
            "entityType", entityType,
            "sampleData", Map.of(
                "id", "sample-id",
                "name", "Sample " + entityType
            )
        ));
    }
}
